# Generated by Django 3.2 on 2021-05-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
