# Generated by Django 3.2 on 2021-05-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_auto_20210521_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
