# Generated by Django 3.2 on 2021-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_alter_user_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='images'),
        ),
    ]
