# Generated by Django 3.2 on 2021-05-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0024_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
