# Generated by Django 3.2 on 2021-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0025_auto_20210522_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hey there...', max_length=40),
        ),
    ]
